version: "2.2"
services:
  db:
    image: postgres
    restart: always
    env_file:
      - db.env
    volumes:
      - './data/db-data:/var/lib/postgresql/data/'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U savapage"]
      interval: 5s
      timeout: 5s
      retries: 5

  savapage:
    build: ./savapage
    container_name: savapage
    ports:
      - "8632:8632/tcp"
      - "631:631/tcp"
    env_file:
      - savapage.env
    volumes:
      - './data/server:/opt/savapage/server/'
      - './data/etc/cups/etc/cups/'
    mem_limit: "1g"
    restart: "always"
    depends_on:
      db:
        condition: service_healthy

volumes:
  server:
  db-data:

