version: "3.0"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=savapage
      - POSTGRES_PASSWORD=MusterSavapage
      - POSTGRES_DB=savapage
    networks:
      internal:
    volumes:
      - './data/db-data:/var/lib/postgresql/data/'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U savapage"]
      interval: 5s
      timeout: 5s
      retries: 5

  savapage:
    image: netzint/savapage:latest
    restart: always
    env_file:
      - savapage.env
    networks:
      internal:
    volumes:
      - './data/server:/opt/savapage/server/'
      - './data/etc/cups:/etc/cups/'
      - './data/usr/lib/cups:/usr/lib/cups/'
    depends_on:
      db:
        condition: service_healthy

networks:
  internal: