#!/bin/bash
# vim: set ts=4 sts=4 sw=4 et:

DB_NAME="${DB_NAME:-empty}"
DB_USER="${DB_USER:-empty}"
DB_PASSWORD="${DB_PASSWORD:-empty}"

DEFAULT_LOCALE="${DEFAULT_LOCALE:-}"
DEFAULT_PAPERSIZE="${DEFAULT_PAPERSIZE:-}"
GLOBAL_CURRENCYCODE="${GLOBAL_CURRENCYCODE:-}"
AUTH_METHOD="${AUTH_METHOD:-}"
AUTH_LDAP_SCHEMA_TYPE="${AUTH_LDAP_SCHEMA_TYPE:-}"
AUTH_LDAP_ADMIN="${AUTH_LDAP_ADMIN:-}"
AUTH_LDAP_PASSWORD="${AUTH_LDAP_PASSWORD:-}"
AUTH_LDAP_SERVER="${AUTH_LDAP_SERVER:-}"
AUTH_LDAP_BASEDN="${AUTH_LDAP_BASEDN:-}"
AUTH_LDAP_PORT="${AUTH_LDAP_PORT:-}"
AUTH_LDAP_USESSL="${AUTH_LDAP_USESSL:-}"
AUTH_LDAP_SSL_HOSTNAME_VERIFICATION_DISABLE="${AUTH_LDAP_SSL_HOSTNAME_VERIFICATION_DISABLE:-}"
AUTH_LDAP_TRUST_SELFSIGNED_CERT="${AUTH_LDAP_TRUST_SELFSIGNED_CERT:-}"
MAIL_SMTP_HOST="${MAIL_SMTP_HOST:-}"
MAIL_SMTP_PORT="${MAIL_SMTP_PORT:-}"
MAIL_SMTP_USERNAME="${MAIL_SMTP_USERNAME:-}"
MAIL_SMTP_PASSWORD="${MAIL_SMTP_PASSWORD:-}"
MAIL_SMTP_MAILFROM_ADRESS="${MAIL_SMTP_MAILFROM_ADRESS:-}"
MAIL_SMTP_SECURITY="${MAIL_SMTP_SECURITY:-}"
SAVAPAGE_USER_PW="${SAVAPAGE_USER_PW:-}"

LDAP_RADIUS_ACCESS_GROUP="${LDAP_RADIUS_ACCESS_GROUP:-}"
RADIUS_CLIENT_CREDENTIALS="${RADIUS_CLIENT_CREDENTIALS:-}"

## to turn on debugging, use "-x -f -l stdout"
#RADIUSD_ARGS="${RADIUSD_ARGS:--f -l stdout}"
#
server.properties_subst() {
    sed -i -e "s/${1}/${2}/g" /opt/savapage/serverBuiltin/server.properties
}
#
#mschap_subst() {
#    sed -i -e "s/${1}/${2}/g" /etc/raddb/mods-available/mschap
#}
#
#krb5_subst() {
#    sed -i -e "s/${1}/${2}/g" /etc/krb5.conf
#}
#
#samba_subst() {
#    sed -i -e "s/${1}/${2}/g" /etc/samba/smb.conf
#}

#cups_subst() {
#echo "cups subst"
#}

## substitute variables into LDAP configuration file

persistantFiles="admin.properties jmxremote.access jmxremote.ks jmxremote.password jmxremote.properties"
persistantFolders="custom data examples ext lib logs tmp"
staticFolders="bin"
staticFiles="server.properties"

for file in $persistantFiles
do
    if [ ! -f /opt/savapage/server/$file ]; then
    cp /opt/savapage/serverBuiltin/$file /opt/savapage/server/$file
    fi
done

for folder in $persistantFolders
do
    if [ ! -f /opt/savapage/server/$folder ]; then
    cp -R /opt/savapage/serverBuiltin/$folder /opt/savapage/server/$folder
    fi
done

for file in $staticFiles
do
    if [ ! -e /opt/savapage/server/$file ]; then
    ln -s /opt/savapage/serverBuiltin/$file /opt/savapage/server/$file
    fi
done

for folder in $staticFolders
do
    if [ ! -e /opt/savapage/server/$folder ]; then
    ln -s /opt/savapage/serverBuiltin/$folder /opt/savapage/server/$folder
    fi
done


if [ ! -f /etc/cups/cupsd.conf ]; then
	  cp -rpn /etc/cups-skel/* /etc/cups/
fi

if [ ! -d /usr/lib/cups/filter ]; then
	  cp -rpn /usr/lib/cups-skel/* /usr/lib/cups/
fi

# set savapage posix password
echo -e "$SAVAPAGE_USER_PW\n$SAVAPAGE_USER_PW" | passwd savapage

server.properties_subst "@DB_NAME@" "${DB_NAME}"
server.properties_subst "@DB_USER@" "${DB_USER}"
server.properties_subst "@DB_PASSWORD@" "${DB_PASSWORD}"

mv /opt/savapage/server/bin/linux-x64/app-server /opt/savapage/server/bin/linux-x64/app-server-daemon
cp /template/app-server_interactive /opt/savapage/server/bin/linux-x64/app-server

chown -R savapage /opt/savapage
chmod +x /opt/savapage/server/bin/linux-x64/app-server


echo "check database"
sudo -u savapage /opt/savapage/server/bin/linux-x64/savapage-db --db-check

if [ $? == 9 ]; then
    # initiate database
    echo "Initiate database"
    sudo -u savapage /opt/savapage/server/bin/linux-x64/savapage-db --db-init
fi


echo "start daemon for setting changes"
/opt/savapage/server/bin/linux-x64/app-server-daemon start &


until /opt/savapage/server/bin/linux-x64/savapage-cmd --get-config-property --name system.default-locale
do
  echo "savapage service not ready yet"
  sleep 1
done

# overwrite settings defined in docker-compose
# local settings

echo "sync users and groups"
/opt/savapage/server/bin/linux-x64/savapage-cmd --sync-users-and-groups

# using database tool directly because of permission problems
echo "set web-print.enable"
export PGPASSWORD=$DB_PASSWORD
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name web-print.enable --value Y
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = 'Y'  WHERE property_name = 'web-print.enable';"
echo "set system.default-papersize"
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$DEFAULT_PAPERSIZE'  WHERE property_name = 'system.default-papersize';"

#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name system.default-papersize --value $DEFAULT_PAPERSIZE
#system.default-papersize

echo "set system.default-locale"
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name system.default-locale --value $DEFAULT_LOCALE
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$DEFAULT_LOCALE'  WHERE property_name = 'system.default-locale';"

echo "set financial.global.currency-code"
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name financial.global.currency-code --value $GLOBAL_CURRENCYCODE
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$GLOBAL_CURRENCYCODE'  WHERE property_name = 'financial.global.currency-code';"

# ldap settings
echo "set auth.method"
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name auth.method --value $AUTH_METHOD
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$AUTH_METHOD  WHERE property_name = 'auth.method';"

echo "set ldap.schema.type"
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name ldap.schema.type --value $AUTH_LDAP_SCHEMA_TYPE
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$AUTH_LDAP_SCHEMA_TYPE'  WHERE property_name = 'ldap.schema.type';"

echo "set auth.ldap.host"
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name auth.ldap.host --value $AUTH_LDAP_SERVER
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$AUTH_LDAP_SERVER'  WHERE property_name = 'auth.ldap.host';"

echo "set auth.ldap.admin-dn"
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name auth.ldap.admin-dn --value $AUTH_LDAP_ADMIN
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$AUTH_LDAP_ADMIN'  WHERE property_name = 'auth.ldap.admin-dn';"

echo "set auth.ldap.admin-password"
/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name auth.ldap.admin-password --value $AUTH_LDAP_PASSWORD

echo "set auth.ldap.basedn"
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name auth.ldap.basedn --value $AUTH_LDAP_BASEDN
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$AUTH_LDAP_BASEDN'  WHERE property_name = 'auth.ldap.basedn';"

echo "set auth.ldap.port"
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name auth.ldap.port --value $AUTH_LDAP_PORT
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$AUTH_LDAP_PORT'  WHERE property_name = 'auth.ldap.port';"

echo "set auth.ldap.use-ssl "
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name auth.ldap.use-ssl --value $AUTH_LDAP_USESSL
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$AUTH_LDAP_USESSL'  WHERE property_name = 'auth.ldap.use-ssl';"

echo "set auth.ldap.ssl.hostname-verification-disable"
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name auth.ldap.ssl.hostname-verification-disable --value $AUTH_LDAP_SSL_HOSTNAME_VERIFICATION_DISABLE
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$AUTH_LDAP_SSL_HOSTNAME_VERIFICATION_DISABLE'  WHERE property_name = 'auth.ldap.ssl.hostname-verification-disable';"

echo "set auth.ldap.use-ssl.trust-self-signed "
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name auth.ldap.use-ssl.trust-self-signed  --value $AUTH_LDAP_TRUST_SELFSIGNED_CERT
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$AUTH_LDAP_TRUST_SELFSIGNED_CERT'  WHERE property_name = 'auth.ldap.use-ssl.trust-self-signed';"

#echo "set ldap.schema.nested-group-search"
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name ldap.schema.nested-group-search  --value '(&(memberOf={0})(objectCategory=group))'

# mail settings
echo "set mail.smtp.host"
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name mail.smtp.host --value $MAIL_SMTP_HOST
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$MAIL_SMTP_HOST'  WHERE property_name = 'mail.smtp.host';"

#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name mail.smtp.port --value $MAIL_SMTP_PORT
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$MAIL_SMTP_PORT'  WHERE property_name = 'mail.smtp.port';"

echo "set mail.smtp.username "
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name mail.smtp.username --value $MAIL_SMTP_USERNAME
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$MAIL_SMTP_USERNAME'  WHERE property_name = 'mail.smtp.username';"

echo "set mail.from.address"
#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name mail.from.address --value $MAIL_SMTP_MAILFROM_ADRESS
psql -h db -U savapage  -c "UPDATE tbl_config SET property_value = '$MAIL_SMTP_MAILFROM_ADRESS'  WHERE property_name = 'mail.from.address';"

echo "set mail.smtp.password "
/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name mail.smtp.password --value $MAIL_SMTP_PASSWORD

#/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name mail.smtp.security --value $MAIL_SMTP_SECURITY



echo "stop daemon after setting changes"
/opt/savapage/server/bin/linux-x64/app-server-daemon stop

#run cups in nondemand mode
/usr/sbin/cupsd -f &
#exec /usr/local/bin/tini -- /usr/sbin/cupsd -f

echo "preparing container finished, starting savapage app-server"
exec /usr/local/bin/tini -- /opt/savapage/server/bin/linux-x64/app-server start

